export type CatalogOptionsType =
  | "ActiveProjects"
  | "ActiveWarehouses"
  | "Automatization"
  | "Brand"
  | "BusinessLine"
  | "BusinessLineService"
  | "CommercialTerm"
  | "CommissionStatus"
  | "CompanyIssuer"
  | "Contacts"
  | "ContactType"
  | "Country"
  | "CurrencyType"
  | "CustomerCategory"
  | "CustomerCategoryType"
  | "CustomerCode"
  | "CustomerType"
  | "EnergyQuality"
  | "Family"
  | "FiscalType"
  | "IntegralProject"
  | "InventoryAdjustmentReason"
  | "InvoiceRequestStatus"
  | "InventoryMovementIssueType"
  | "InventoryMovementReceiptType"
  | "InventoryTransferReason"
  | "InvoiceStatus"
  | "InvoiceType"
  | "LeadType"
  | "MaterialRequestType"
  |"MaterialRequestStatus"
  | "Networking"
  | "Other"
  | "PaymentComplementStatus"
  | "PhysicalSecurity"
  | "ProjectCode"
  | "ProjectManager"
  | "QuoteStatus"
  | "SaleType"
  | "SoundVideo"
  | "SubFamilies"
  | "State"
  | "States"
  | "StructuredCabling"
  | "UnitOfMeasure"
  | "VerticalMarket"
  | "ActiveCustomers"
  | "Year"
  | "WarehouseType"

export interface ICatalogItem {
  id: number;
  code: string | null;
  name: string;
}
